version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: semiannually # monthly, quarterly, semiannually, yearly - Every 1, 3, 6 or 12 months
    assignees:
      - ahakola
